### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by GarretReece** [trailofbits/streamalert#1]
Documentation exists that lays out (as needed)
* [ ] ~~building~~
* [x] configuring
* [ ] ~~deploying~~
* [ ] ~~use cases~~
* [ ] ~~design decisions~~
* [x] limitations encountered
* [x] workarounds
* [ ] ~~edge cases~~

**Comment by MatthewARinehart** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Airbnb StreamAlert](https://trello.com/c/KASdA67v/40-airbnb-streamalert)

**Comment by MatthewARinehart** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stripe Santa Replacement (Sinter)](https://trello.com/c/u2oOBCFZ/47-stripe-santa-replacement-sinter)

**Comment by mike-myers-tob** [comment]
Followed up with Airbnb today, this is completed.
