### ISSUE TITLE
Create test environment

### ISSUE THREAD

**Issue by GarretReece** [trailofbits/streamalert#2]
Set up test environment for StreamAlert

Minimum environment to get with development:
* [x] install prerequisites for streamalert
* [x] create slack workspace

Necessary for full deployment testing
* [x] create aws account
* [x] define your AWS account
* [x] Define your clusters
* [x] Define your datasources
* [x] Define your schemas
* [x] Configure your kinesis stream/firehose
* [x] Configure your lambda settings
* [x] Write your rules
* [x] Configure your outputs
* [x] deploy streamalert
* [ ] configure slack app
* [ ] deploy slack app

**Comment by jacknagz** [comment]
@GarretReece what's the issue you're having with `init`?

**Comment by GarretReece** [comment]
I worked it out this morning; the profile for the aws account needs access to the `dynamodb` and `glue` services

**Comment by GarretReece** [comment]
The change in PR 757 on the main repository fixed the final blocker, testing works end to end now
